os: linux
dist: trusty
sudo: required
sudo: required

language: node_js
node_js:
  - "8"
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
- docker-compose build

script: "true"

deploy:
  - provider: script
    script: 
      docker-compose push;
      docker-compose -f docker-compose-heroku.yml build;
      sh ./api-gateway/deploy_heroku.sh;
      sh ./contacts-service/deploy_heroku.sh;
      sh ./users-service/deploy_heroku.sh;
    on:
      branch: master
    skip_cleanup: true