os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "8"
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com

install:
- docker-compose build

script: "true"

deploy:
  - provider: script
    script: bash deploy.sh
    on:
      branch: master
    skip_cleanup: true