sudo: required

language: node_js
node_js:
  - "8"
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
- docker-compose build

script: "true"

deploy:
  - provider: script
    script: docker-compose push
    on:
      branch: master
    skip_cleanup: true