sudo: required

services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
- docker-compose pull
- docker-compose build

# script:
#   - docker-compose run --no-deps -rm api

deploy:
  - provider: script
    script: bash ./deploy.sh
    on:
      branch: master
    skip_cleanup: true