sudo: required

language: node_js
node_js:
  - "8"
services:
  - docker

install:
- docker-compose pull
- docker-compose build

before_script: ls -R

script: "true"

deploy:
  - provider: script
    script: bash ./deploy.sh
    on:
      branch: master
    skip_cleanup: true