version: "3"

services:    
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5672"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: none
  
  api_gateway:
    image: catamo/srtv-addressbook_api-gateway
    build: ./api-gateway
    container_name: api_gateway
    volumes:
      - "./api-gateway:/home/appuser/app"
    working_dir: "/home/appuser/app"
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    restart: on-failure
    command: npm run start
    env_file: ./api-gateway/.env

  users_service:
    image: catamo/srtv-addressbook_users-service
    build: ./users-service
    container_name: ms_users
    volumes:
      - "./users-service:/home/appuser/app"
    working_dir: "/home/appuser/app"
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    restart: on-failure
    command: npm run start
    env_file: ./users-service/.env

  contacts_service:
    image: catamo/srtv-addressbook_contacts-service
    build: ./contacts-service
    container_name: ms_contacts
    volumes:
      - "./contacts-service:/home/appuser/app"
    working_dir: "/home/appuser/app"
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
    restart: on-failure
    command: npm run start 
    env_file: ./contacts-service/.env