version: "3"

services:      
  api_gateway:
    image: registry.heroku.com/srtv-addressbook-catamo-victor/web
    build: ./api-gateway
    container_name: api_gateway
    volumes:
      - "./api-gateway:/home/appuser/app"
    working_dir: "/home/appuser/app"
    command: npm run start

  users_service:
    image: registry.heroku.com/srtv-addressbook-msusers/worker
    build: ./users-service
    container_name: ms_users
    volumes:
      - "./users-service:/home/appuser/app"
    working_dir: "/home/appuser/app"
    command: npm run start

  contacts_service:
    image: registry.heroku.com/srtv-addressbook-mscontacts/worker
    build: ./contacts-service
    container_name: ms_contacts
    volumes:
      - "./contacts-service:/home/appuser/app"
    working_dir: "/home/appuser/app"
    command: npm run start 