version: "3"

services:
  default:
    build: ./api-gateway
    container_name: api_gateway
    volumes:
      - "./api-gateway:/home/appuser/app"
    working_dir: "/home/appuser/app"
    ports:
      - "5000:5000"
    command: npm run start

  users_service:
    build: ./users-service
    container_name: ms_users
    volumes:
      - "./users-service:/home/appuser/app"
    working_dir: "/home/appuser/app"
    ports:
      - "3000:3000"
    command: npm run start

  contacts_service:
    build: ./contacts-service
    container_name: ms_contacts
    volumes:
      - "./contacts-service:/home/appuser/app"
    working_dir: "/home/appuser/app"
    ports:
      - "4000:4000"
    command: npm run start