#%RAML 1.0
title: Users Service
version: v1
baseUri: /users
uses:
  object: types.raml

types:
  Users: object.User []

resourceTypes:
  GET:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>


/:
  type:  { GET: {item : Users } }

  /{user_id}:
    type:  { GET: {item : User } }
