#%RAML 1.0 Library

types:
  User:
    properties:
      id: string
      name: string
      surname: string
      email: string
      password: string
    example:
      id: "123"
      name: "Victor"
      surname: "Catamo"
      email: "victor.catamo.rojas@gmail.com"
      password: "pass"